config/routes.rb
MooShop::Application.routes.draw do
  root :to => 'pages#home'

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :categories

  resources :orders, :except => [ :destroy ]

  resources :products do
    collection do
      get :export
      post :import
    end
  end

  scope :pages, :path => 'pages' do
    get 'home', :to => 'pages#home', :as => 'home'
    get 'contacts', :to => 'pages#contacts', :as => 'contacts'
  end

  scope :cart, :path => 'cart' do
    get 'add/:product_id' => 'cart#add_to_cart', :as => 'add_to_cart'
    get 'remove/:product_id' => 'cart#remove_from_cart', :as => 'remove_from_cart'
    get '/' => 'cart#show', :as => 'cart'
    get 'checkout' => 'cart#checkout', :as => 'checkout'
  end

  namespace :admin do
    resources :users
    resources :orders, :only => [ :edit, :index ]
    resources :products
    resources :categories, :only => [ :new, :edit, :index ]

    get :index
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
    def add_to_cart
        product = Product.find(params[:product_id])

        @shopping_cart.add_product product

        if request.referer
            redirect_to request.referer
        else
            redirect_to url_for(:controller => :cart, :action => :show)
        end
    end

    def remove_from_cart
        product = Product.find params[:product_id]

        @shopping_cart.remove_product product

        if request.referer
            redirect_to request.referer
        else
            redirect_to url_for(:controller => :cart, :action => :show)
        end
    end

    def show
    end

    def checkout
        if user_signed_in?
            redirect_to new_order_path
        end
    end
end

app/views/cart/checkout.html.slim
h1 To checkout, you must sign in

.ui.two.column.page.grid
    .column
        h2 Sign in

        .ui.form.item
            = form_for(User.new, :url => session_path(User)) do |f|
                .field
                    .ui.left.labeled.icon.input
                        = f.email_field :email, :autofocus => true, :placeholder => "E-mail"

                        i.user.icon
                        .ui.corner.label
                            i.icon.asterisk

                .field
                    .ui.left.labeled.icon.input
                        = f.password_field :password, :placeholder => "Password"

                        i.lock.icon
                        .ui.corner.label
                            i.icon.asterisk

                - if Devise.mappings[:user].rememberable?
                    .field.inline
                        .ui.checkbox
                            = f.check_box :remember_me
                            label for="user_remember_me"

                        label for="user_remember_me"
                            |Remember me

                = f.submit "Sign in", :class => "ui blue submit button"

                - if Devise.mappings[:user].recoverable?
                    = link_to "Forgot your password?", new_password_path(User), :class => 'ui green submit button'

    .column
        h2 Register now
        .ui.form.item
            = form_for(User.new, :url => registration_path(User)) do |f|
                .field
                    .ui.left.labeled.icon.input
                        = f.email_field :email, :autofocus => true, :placeholder => "E-mail"

                        i.user.icon
                        .ui.corner.label
                            i.icon.asterisk

                .field
                    .ui.left.labeled.icon.input
                        = f.password_field :password, :placeholder => "Password"

                        i.lock.icon
                        .ui.corner.label
                            i.icon.asterisk

                .field
                    .ui.left.labeled.icon.input
                        = f.password_field :password_confirmation, :placeholder => "Password again, please"

                        i.lock.icon
                        .ui.corner.label
                            i.icon.asterisk

                = f.submit "Sign up", :class => "ui blue submit button"

app/views/cart/show.html.slim
table.ui.sortable.table.segment
    thead
        tr
            th
                |Title

            th
                |Price

            th
                |In the cart

    tbody
        - @shopping_cart.counted_products.each do |product, count|
            tr
                td
                    = product.title
                td
                    = product.base_price

                td
                    = count

                    a.circular.right.floated.red.tiny.ui.icon.button href="#{ remove_from_cart_path product.id }"
                        i.icon.delete

a.ui.button.green href="#{ checkout_path }"
    | Checkout