config/routes.rb
MooShop::Application.routes.draw do
  root :to => 'pages#home'

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :categories

  resources :orders, :except => [ :destroy ]

  resources :products do
    collection do
      get :export
      post :import
    end
  end

  scope :pages, :path => 'pages' do
    get 'home', :to => 'pages#home', :as => 'home'
    get 'contacts', :to => 'pages#contacts', :as => 'contacts'
  end

  scope :cart, :path => 'cart' do
    get 'add/:product_id' => 'cart#add_to_cart', :as => 'add_to_cart'
    get 'remove/:product_id' => 'cart#remove_from_cart', :as => 'remove_from_cart'
    get '/' => 'cart#show', :as => 'cart'
    get 'checkout' => 'cart#checkout', :as => 'checkout'
  end

  namespace :admin do
    resources :users
    resources :orders, :only => [ :edit, :index ]
    resources :products
    resources :categories, :only => [ :new, :edit, :index ]

    get :index
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  STATUSES = [ :new, :processing, :completed, :cancelled ]
  PAYMENT_METHODS = [ 'Cash', 'Master Card', 'Visa' ]

  belongs_to :user
  has_many :items, :dependent => :destroy, :foreign_key => :order_id, :class_name => 'OrderItem'

  validates :payment_method,
            :inclusion => {
                :in => PAYMENT_METHODS,
                :message => 'was not selected'
            }

  validates :address,
            :presence => {
                :message => 'to deliver was not set'
            }

  def status
    (read_attribute :status).to_sym
  end

  def status=(value)
    value = value.to_sym
    errors[:status] << "Unrecognized status `#{ value }`" unless STATUSES.include? value
    write_attribute :status, value
  end

  def total_price
      prices = items.map { |item| item.price.present? ? item.price.to_f : 0.0 }
      prices = prices.present? ? prices : [ 0.0 ]
      prices.inject :+
  end

  def total_price_s
      "$ %.2f" % total_price
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    include Administrative

    def index
        @orders = Order.page(@page).per(@per_page)
    end

    def edit
        @order = Order.find(params[:id])
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, :only => [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    unless user_signed_in?
      redirect_to new_registration_path
    end

    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = current_user.orders.new(order_params)

    @shopping_cart.counted_products.each do |product, amount|
        order_item = OrderItem.from_products product, amount
        order_item.save

        @order.items << order_item
    end

    @order.status = :new

    respond_to do |format|
      if @order.save
        @shopping_cart.clear!

        format.html { redirect_to @order, :notice => 'Order was successfully created.' }
        format.json { render :action => 'show', :status => :created, :location => @order }
      else
        format.html { render :action => 'new' }
        format.json { render :json => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, :notice => 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => 'edit' }
        format.json { render :json => @order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      permit = [ :address, :payment_method ]

      permit << :status if action_name == 'update'

      params.require(:order).permit(*permit)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/edit.html.slim
h1
    |Edit order

table.ui.table.segment
    thead
        tr
            th.center.aligned colspan="3"
                |Order items:

        tr
            th
                |Title

            th
                |Amount

            th
                |Price

    tbody
        - @order.items.each do |item|
            tr
                td
                    = item.title

                td
                    = item.amount

                td
                    = item.price

    tfoot
        tr
            th
                |&zwnj;

            th
                |Items: #{ @order.items.count }

            th
                |Total: #{ @order.total_price_s }

.ui.form.segment
    = form_for @order do |f|
        .field
            .ui.blue.labeled.icon.top.left.pointing.dropdown.button
                = f.hidden_field :status
                i.cart.icon
                span.text
                    |Order status

                .menu
                    - Order::STATUSES.each do |status|
                        .item
                            i.edit.icon
                            = status.to_s.titleize

        .field
            = f.submit :class => 'ui green button'

app/views/admin/orders/index.html.slim
h1
    |Manage orders

table.ui.sortable.table.segment
    thead
        tr
            th
                |User

            th
                |Created

            th
                |Total

            th
                |Status

    tbody
        - @orders.each do |order|
            tr
                td
                    = link_to order.user.full_name, admin_user_path(order.user)

                td
                    = link_to "#{ time_ago_in_words order.created_at } ago", edit_admin_order_path(order)

                td
                    = order.total_price_s

                td
                    = order.status