config/routes.rb
MooShop::Application.routes.draw do
  root :to => 'pages#home'

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :categories

  resources :orders, :except => [ :destroy ]

  resources :products do
    collection do
      get :export
      post :import
    end
  end

  scope :pages, :path => 'pages' do
    get 'home', :to => 'pages#home', :as => 'home'
    get 'contacts', :to => 'pages#contacts', :as => 'contacts'
  end

  scope :cart, :path => 'cart' do
    get 'add/:product_id' => 'cart#add_to_cart', :as => 'add_to_cart'
    get 'remove/:product_id' => 'cart#remove_from_cart', :as => 'remove_from_cart'
    get '/' => 'cart#show', :as => 'cart'
    get 'checkout' => 'cart#checkout', :as => 'checkout'
  end

  namespace :admin do
    resources :users
    resources :orders, :only => [ :edit, :index ]
    resources :products
    resources :categories, :only => [ :new, :edit, :index ]

    get :index
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :products
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
    include Administrative

    def index
        @categories = Category.page(@page).per(@per_page)
    end

    def new
        @category = Category.new
    end

    def edit
        @category = Category.find(params[:id])
    end

    def show
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
      @products = @category.products.page(params[:page] || 1)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.slim
h1
    |Categories

- @categories.each do |category|
    a.ui.label href="#{ category_path(category) }"
        = category.title

        .detail
            = category.products.count

/= link_to 'New Category', new_category_path

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.slim
h1.uk-heading-large
    = @category.title

- if @products.count > 0
    = render :partial => 'products/list', :locals => { :products => @products }

    .with.content.centered
        = paginate @products