config/routes.rb
MooShop::Application.routes.draw do
  root :to => 'pages#home'

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  resources :categories

  resources :orders, :except => [ :destroy ]

  resources :products do
    collection do
      get :export
      post :import
    end
  end

  scope :pages, :path => 'pages' do
    get 'home', :to => 'pages#home', :as => 'home'
    get 'contacts', :to => 'pages#contacts', :as => 'contacts'
  end

  scope :cart, :path => 'cart' do
    get 'add/:product_id' => 'cart#add_to_cart', :as => 'add_to_cart'
    get 'remove/:product_id' => 'cart#remove_from_cart', :as => 'remove_from_cart'
    get '/' => 'cart#show', :as => 'cart'
    get 'checkout' => 'cart#checkout', :as => 'checkout'
  end

  namespace :admin do
    resources :users
    resources :orders, :only => [ :edit, :index ]
    resources :products
    resources :categories, :only => [ :new, :edit, :index ]

    get :index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    before_filter :set_shopping_cart, :cancan_strong_attributes

    protected

    def set_shopping_cart
        if user_signed_in?
            if session.has_key? :shopping_cart
                @shopping_cart = ShoppingCart.new current_user, session
            else
                @shopping_cart = ShoppingCart.new current_user
            end
        else
            @shopping_cart = ShoppingCart.new session
        end
    end

    def cancan_strong_attributes
        resource = controller_name.singularize.to_sym
        method = "#{resource}_params"

        params[resource] &&= send(method) if respond_to?(method, true)
    end

    def after_sign_in_path_for(resource_or_scope)
        home_path
    end

    def after_sign_up_path_for(resource_or_scope)
        home_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_admin_top_menu.html.slim
.ui.menu
    a.item href="/"
        i.home.icon
        |Shop home

    .ui.simple.dropdown.item
        i.dashboard.icon
        a href=admin_index_path
            |Admin dashboard

        .menu
            a.item href=admin_products_path
                |Products

            a.item href=admin_categories_path
                |Categories

            a.item href=admin_orders_path
                |Orders

            a.item href=admin_users_path
                |Users

    - if Category.count > 0
        .ui.simple.dropdown.item
            i.tags.icon
            a href=categories_path
                |Categories

            .menu
                - Category.all.each do |category|
                    a.item href="#{ category_path(category) }"
                        = category.title

    .right.menu
        .borderless.item
            .ui.icon.input
                input type="typext" name="query" placeholder="Search..." id="search"
                i.search.link.icon

        - unless @shopping_cart.empty?
            .ui.simple.dropdown.item
                i.cart.icon
                |Your cart

                .menu
                    - @shopping_cart.counted_products.each do |product, count|
                        a.item href="#{ product_path(product.id) }"
                            strong
                                = "#{ count } x"
                            |&nbsp;
                            = "#{ product.title }"
                            |&nbsp;
                            strong
                                = "(#{ product.price })"

                    .item.with.centered.content
                        a.ui.horizontal.label.blue href="#{ checkout_path }"
                            |Checkout

        - if user_signed_in?
            .ui.item
                i.user.icon

                a.ui.horizontal.label.blue href="#{ edit_user_registration_path }"
                    |Settings

                a.ui.horizontal.label.green href="#{ destroy_user_session_path }"
                    |Sign out
        - else
            .ui.simple.dropdown.item
                i.user.icon

                a.ui.horizontal.label.blue href="#{ new_user_session_path }"
                    |Sign in

                strong
                    |or

                a.ui.horizontal.label.green href="#{ new_user_registration_path }"
                    |Sign up

                /.menu
                    .ui.form.item
                        .field
                            .ui.left.labeled.icon.input
                                input type="text" placeholder="E-mail"
                                i.user.icon
                                .ui.corner.label
                                    i.icon.asterisk

                        .field
                            .ui.left.labeled.icon.input
                                input type="password" placeholder="Password"
                                i.lock.icon
                                .ui.corner.label
                                    i.icon.asterisk

                        input.ui.blue.submit.button type="submit" value="Sign in"

app/views/application/_user_top_menu.html.slim
.ui.menu
    a.item href="/"
        i.home.icon
        |Home

    - if Category.count > 0
        .ui.simple.dropdown.item
            i.tags.icon
            a href="#{ categories_path }"
                |Categories

            .menu
                - Category.all.each do |category|
                    a.item href="#{ category_path(category) }"
                        = category.title

    .right.menu
        .borderless.item
            .ui.icon.input
                input type="typext" name="query" placeholder="Search..." id="search"
                i.search.link.icon

        - unless @shopping_cart.empty?
            .ui.simple.dropdown.item
                i.cart.icon
                |Your cart

                .menu
                    - @shopping_cart.counted_products.each do |product, count|
                        a.item href="#{ product_path(product.id) }"
                            strong
                                = "#{ count } x"
                            |&nbsp;
                            = "#{ product.title }"
                            |&nbsp;
                            strong
                                = "(#{ product.price })"

                    .item.with.centered.content
                        a.ui.horizontal.label.blue href="#{ checkout_path }"
                            |Checkout

        - if user_signed_in?
            i.user.icon

            a.ui.horizontal.label.blue href="#{ edit_user_registration_path }"
                |My profile

            a.ui.horizontal.label.green href="#{ destroy_user_session_path }"
                |Sign out
        - else
            i.user.icon

            a.ui.horizontal.label.blue href="#{ new_user_session_path }"
                |Sign in

            strong
                |or

            a.ui.horizontal.label.green href="#{ new_user_registration_path }"
                |Sign up